version: '3.8'
services:
  new_postgres:
    container_name: container-new-pg
    image: postgres:16.2
    hostname: new_postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: new_admin
      POSTGRES_PASSWORD: new_root
      POSTGRES_DB: newdb
    volumes:
      - new_postgres_data:/var/lib/postgresql/data
    networks:
      - keycloak_network
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "5050:80"
    networks:
      - keycloak_network
    restart: unless-stopped

volumes:
  new_postgres_data:
    driver: local

networks:
  keycloak_network:
    driver: bridge
# Another test change
